[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
anyhow = "1.0"
arrayvec = "0.7"
clap = { version = "4", features = ["derive"]}
lazy_static = "1.4"
nom = "7.1"
rayon = "1.8"

[profile.release]
panic = 'abort'
